### ISSUE TITLE
The command shown in Codelab documentation to run locally shouldn't work with docker-machine

### ISSUE THREAD

**Issue by nagachika** [kazunori279/TensorFlow-Intro#6]
The Codelab documentation show the command to run codelab locally on Mac OS/Linux like below.

https://cloud.google.com/datalab/docs/quickstarts/quickstart-local
```
docker run -it -p "127.0.0.1:8081:8080" -v "${HOME}:/content" \
  -e "PROJECT_ID=<PROJECT_ID>" \
  gcr.io/cloud-datalab/datalab:local
```

But it didn't work if you use docker-machine & VirtualBox to run docker engine. Because on such environments, the docker containers run on the VM on VirtualBox and it has different IP address.

Showing some note for docker-machine user would help.

In my case, the command like below work well.

```
docker run -it -p "8081:8080" -v "${HOME}:/content" \
  -e "PROJECT_ID=<PROJECT_ID>" \
  gcr.io/cloud-datalab/datalab:local
```

And you should access to `http://${VM IP addr}:8081` instead of `http://localhost:8081`.
VM IP addr is shown by command
```
docker-machine ip (machine name)
```

**Comment by kazunori279** [comment]
Thanks, I added a link to this issue for docker machine users.
