### ISSUE TITLE
Incompatibility Between Docker and Microsoft Home

### ISSUE THREAD

**Issue by QamraKhan** [kazunori279/TensorFlow-Intro#9]
People on Windows Home may have compatibility issues with Docker. This is because you can only download Docker Toolkit and not Docker 1.12.0 or later which you need for this codelab. However, you can still run Cloud Datalab notebooks on Google Cloud Platform.

If you are having issues running this with Docker would suggest you to do the following:

1. Enable Billing and ensure you have APIs enabled for Google Cloud Platform as well as Compute Engine API .

2. Make sure you download the Google Cloud SDK.

3. Login to Google on the Google Cloud SDK Shell with command: $ gcloud auth login

4.  Make sure you set your project ID:   $ gcloud config set project PROJECT_ID

5. Follow the rest of the steps here (but some of the g Cloud SDK Shell commands are not intuitive):
https://cloud.google.com/datalab/docs/quickstarts/quickstart-gcp-frontend

**Comment by kazunori279** [comment]
Thanks. The local Docker version of Datalab will be deprecated soon, so I changed the preparation instruction to use "datalab create" command.
